/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.view.LoginPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.TitleBar',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        padding: '50 0',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Телефонен указател'
            },
            {
                xtype: 'fieldset',
                instructions: 'Телефонен указате на всички служители по горите ',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'txtUser',
                        label: 'Потребител:',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'txtPass',
                        label: 'Парола:',
                        labelWidth: '40%'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'loginBtn',
                margin: '0 auto',
                maxWidth: '50%',
                text: 'Вход'
            }
        ]
    }

});