/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.view.Main', {
    extend: 'Ext.Container',
    alias: 'widget.main',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.Menu'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Телефонен у-тел',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            if(Ext.Viewport.getMenus().left.isHidden()){
                                Ext.Viewport.showMenu('left');
                            }
                            else
                            {
                                Ext.Viewport.hideMenu('left');
                            }
                        },
                        ui: 'plain',
                        iconCls: 'list'
                    }
                ]
            },
            {
                xtype: 'image',
                height: 517,
                src: 'resources/images/home.png'
            }
        ]
    },

    initialize: function() {
        Ext.Viewport.setMenu(this.createMenu(),{
                            side: 'left',
                            reveal: false
                        });
    },

    createMenu: function() {
        var items = [
                    {
                        xtype: 'button',
                        text: 'Начало',
                        iconCls: 'home',
                        cls: 'menu-button',
                        id: 'btnHome'
                    },
                    {
                        xtype: 'button',
                        text: 'Служители в ИАГ',
                        iconCls: 'team',
                        cls: 'menu-button',
                        id: 'btnIag'
                    },
                    {
                        xtype: 'button',
                        text: 'Служители в РДГ',
                        iconCls: 'team',
                        cls: 'menu-button',
                        id: 'btnRdg'
                    },
                    {
                        xtype: 'button',
                        text: 'Служители в МЗХ </br> (РДГ, ДГС и др.)',
                        iconCls: 'team',
                        cls: 'menu-button',
                        id: 'btnPodelenia'
                    },
                    {
                        xtype: 'button',
                        text: 'Търсене по име',
                        iconCls: 'search',
                        cls: 'menu-button',
                        id: 'btnSearchByName'
                    },
                    {
                        xtype: 'button',
                        text: 'Търсене по номер',
                        iconCls: 'search',
                        cls: 'menu-button',
                        id: 'btnSearchByNumber'
                    },
                    {
                        xtype: 'button',
                        text: 'За приложението',
                        iconCls: 'user',
                        cls: 'menu-button',
                        id: 'btnAbout'
                    }
                ];

        return Ext.create('Ext.Menu', {
                    style: 'padding: 50 0 20 0',
                    id: 'menu',
                    width: 280,
                    scrollable: 'vertical',
                    items: items
                });
    }

});