/*
 * File: app/model/PodModel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.model.PodModel', {
    extend: 'Ext.data.Model',
    alias: 'model.podmodel',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'ID'
            },
            {
                name: 'Pod_NameBg'
            },
            {
                name: 'Pod_Tel'
            },
            {
                name: 'Pod_Id'
            },
            {
                name: 'Glav_Pod'
            }
        ]
    }
});