/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.TitleBar'
    ],
    models: [
        'LoginModel',
        'PodModel',
        'UserModel'
    ],
    stores: [
        'IagJsonPStore',
        'LoginStore',
        'PodJsonPStore',
        'PodSubJsonPStore',
        'PodUserJsonPStore',
        'SearchJsonPStore',
        'DetailCardJsonPStore'
    ],
    views: [
        'HomePanel',
        'IagList',
        'IagNavView',
        'IagUserList',
        'LoginPanel',
        'MainTabPanel',
        'MenuPanel',
        'NoConnectionPanel',
        'PodList',
        'PodNavView',
        'PodSubList',
        'PodUserList',
        'RdgList',
        'RdgNavView',
        'SearchFormPanel',
        'Main',
        'AboutPanel'
    ],
    controllers: [
        'CallController',
        'LoginController',
        'MenuController',
        'PodController',
        'RdgController',
        'SearchController',
        'CallMenuController'
    ],
    name: 'Contacts',

    launch: function() {

        //Ext.getStore('IagJsonPStore').load();
        //Ext.getStore('PodJsonPStore').load();


        Ext.create('Contacts.view.MainTabPanel', {fullscreen: true});
    }

});
