/*
 * File: app/controller/CallController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.controller.CallController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.callcontroller',

    config: {
        refs: {
            iaguserlist: {
                selector: 'iaguserlist',
                xtype: 'iaguserlist'
            },
            poduserlist: {
                selector: 'poduserlist',
                xtype: 'poduserlist'
            },
            searchresultuserlist: {
                selector: 'searchresultuserlist',
                xtype: 'searchresultuserlist'
            }
        },

        control: {
            "iaguserlist": {
                itemsingletap: 'onIagListItemSingletap',
                itemdoubletap: 'onListItemDoubletap'
            },
            "poduserlist": {
                itemsingletap: 'onPodListItemSingletap',
                itemdoubletap: 'onPodUsrListItemDoubletap'
            },
            "searchresultuserlist": {
                itemsingletap: 'onSearchResultListItemSingletap',
                itemdoubletap: 'onSearchListItemDoubletap'
            }
        }
    },

    onIagListItemSingletap: function(dataview, index, target, record, e, eOpts) {

        this.callAndEmailFn(record);
    },

    onPodListItemSingletap: function(dataview, index, target, record, e, eOpts) {

        this.callAndEmailFn(record);
    },

    onSearchResultListItemSingletap: function(dataview, index, target, record, e, eOpts) {

        this.callAndEmailFn(record);
    },

    onListItemDoubletap: function(dataview, index, target, record, e, eOpts) {
        this.showEgnFn(record);
    },

    onPodUsrListItemDoubletap: function(dataview, index, target, record, e, eOpts) {
        this.callPhoneFn(record);
    },

    onSearchListItemDoubletap: function(dataview, index, target, record, e, eOpts) {
        this.callPhoneFn(record);
    },

    callAndEmailFn: function(record) {
        Ext.Viewport.setMasked(false);

        var gsm = record.get('GSM'),
            email = record.get('Email'),
            fullname = record.get('Titla') + ' ' + record.get('Name') + ' ' + record.get('Familia'),
            pod = record.get('Podelenie'),
            dlagnost = record.get('Dlagnost'),
            EGN = record.get('EGN'),
            sms = record.get('GSM');

            //без ЕГН
            text = '<P>' + dlagnost + '</p><p>' + pod + '</p><p>' + gsm + '</p><p>' + email + '</p>';

            // с ЕГН
            //text = '<P>ЕГН: ' + EGN + '</p><P>' + dlagnost + '</p><p>' + pod + '</p><p>' + gsm + '</p><p>' + email + '</p>';

        Ext.Msg.show({

            title: fullname,
            //message: this.changeMessageTextAndQuestion(gsm, email, text),
            message: '',
            //width: 500,

            buttons:[
                { text: 'Избери', itemId: 'call', hidden: this.hideButton(gsm) },
                { text: 'Email',  itemId: 'email', hidden: this.hideButton(email) },
                { text: 'sms',  itemId: 'sms', hidden: this.hideButton(sms) },
                { text: 'Затвори', itemId: 'cancel' }
            ],

            fn: function(buttonId) {

                if (buttonId == 'call'){
                    document.location.href = 'tel:'+record.get('GSM');
                } else if (buttonId == 'email'){
                    document.location.href = 'mailto:'+record.get('Email');
                } else if (buttonId == 'sms'){
                    document.location.href = 'sms:'+record.get('GSM');
                    console.log('smsto:' + record.get('GSM'));
                } else if (buttonId == 'cancel'){
                    //console.log('cancel');
                } else {
                    alert('Има някакава грешка');
                }
            }
        });
    },

    hideButton: function(param) {
        if (param === ''){
            return true;
        } else {
            return false;
        }
    },

    changeMessageTextAndQuestion: function(gsm, email, text) {

        if (gsm === '') {
            return text + '<p>Няма въведен телефонен номер</p>';
        } else if ( (gsm === '') && (email === '')){
            return text + '<p>Няма въведени телефонен номер и имейл</p>';
        } else if ( (gsm !== '') && (email === '')){
            return text + '<p>Да избера ли номера ?</p>';
        } else if ( (gsm === '') && (email !== '')){
            return text + '</p><p>Няма въведен телефон номер.</p><p>Можете да изпратите само имейл</p>';
        }else if ( (gsm !== '') && (email !== '')){
            return text + '<p>Да избера ли номера или ще изпратите имейл ?</p>';
        } else {
            alert('Има някаква грешка');
        }

    },

    callPhoneFn: function(record) {
        document.location.href = 'tel:'+record.get('GSM');
    },

    showEgnFn: function(record) {
        Ext.Viewport.setMasked(false);

         var   fullname = record.get('Titla') + ' ' + record.get('Name') + ' ' + record.get('Familia'),
               EGN = record.get('EGN');


        Ext.Msg.show({

            title: fullname,
            message: 'ЕГН: ' + EGN,
            width: 320,
            buttons:[

                { text: 'Затвори', itemId: 'cancel' }
            ],

        });
    }

});