/*
 * File: app/controller/CallMenuController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.controller.CallMenuController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.callmenucontroller',

    config: {
        refs: {
            btnHome: '#btnHome',
            btnIag: '#btnIag'
        },

        control: {
            "btnHome": {
                tap: 'onHomeButtonTap'
            },
            "btnIag": {
                tap: 'onIagButtonTap'
            }
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
        console.log('Tab btnHome');
        Ext.Viewport.hideMenu('left');
        Ext.Viewport.animateActiveItem(Ext.create('Contacts.view.HomePanel'),{type:'flip',duration: 400});
    },

    onIagButtonTap: function(button, e, eOpts) {
        console.log('Tab btnHome');
        this.loadStore('IagJsonPStore', 'Contacts.view.IagNavView');
    },

    loadStore: function(store, view) {
        console.log('Hello');

        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Зареждам ...', indicator:true});
                Ext.getStore(store).load({
                    callback: function(records, operation, success) {
                        if(success)
                        {
                            Ext.Viewport.setMasked(false);
                            Ext.Viewport.hideMenu('left');
                            Ext.Viewport.animateActiveItem(Ext.create(view),{type:'flip',duration: 400});

                            console.log('success');
                        } else {
                            Ext.Viewport.setMasked(false);
                            Ext.Msg.alert('Събщение', 'Проверете връзката с интернет и рестартирайте приложението', Ext.emptyFn);
                        }
                    }
                });
    }

});