/*
 * File: app/controller/SearchController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.controller.SearchController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.searchcontroller',

    config: {
        refs: {
            btnsearch: '#btnSearch',
            searchnavview: 'searchnavview'
        },

        control: {
            "btnsearch": {
                tap: 'onSearchButtonTap'
            }
        }
    },

    onSearchButtonTap: function(button, e, eOpts) {
        console.log('tap');

        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Моля, изчакайте ...', indicator:true});

        var ime = Ext.getCmp('txtSearch').getValue();

        if (ime.length > 2)
        {
            var arr = ime.split(" ");

            var Ime   = arr[0];
            var Fam   = arr[1];

            var store = Ext.getStore('SearchJsonPStore',{
                autoLoad:false,
                url:'https://system.iag.bg/iagSys/resources/php/users.php'
            });
            store.load(
                {
                    params: {
                        Ime: Ime,
                        Fam: Fam
                    },

                    callback: function(records, operation, success) {

                        if(success)
                        {
                            Ext.Viewport.setMasked(false);
                            this.getSearchnavview().push({
                                xtype:'searchresultuserlist',
                                title: 'Списък'
                            });

                        }
                        else
                        {
                            Ext.Viewport.setMasked(false);
                            Ext.Msg.alert('Събщение', 'Няма регистрирана такова лице.', Ext.emptyFn);

                        }
                    },
                    scope: this
                });
        }
        else
        {
            Ext.Msg.alert('Събщение', 'Некоректно търсене. Въведете минимум 3 букви, за да търсите по Име или 2 букви с интервал между тях за търсене по Име и Фамилия ', Ext.emptyFn);
            Ext.Viewport.setMasked(false);
        }


    }

});